.TH "EcatSystem Directory Reference" 3 "Thu Dec 12 2019" "Version 1.0.0" "Dual Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatSystem Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEcat_Elmo\&.h\fP"
.br
.ti -1c
.RI "file \fBEcat_Master\&.h\fP"
.br
.RI "EtherCAT master from SimpleCAT\&. "
.ti -1c
.RI "file \fBEcat_Maxon\&.h\fP"
.br
.RI "Modified version of SimpleCAT\&. "
.ti -1c
.RI "file \fBEcat_Slave\&.h\fP"
.br
.RI "EtherCAT slave base class\&. "
.ti -1c
.RI "file \fBPDOConfig\&.h\fP"
.br
.RI "PDO configuration\&. "
.in -1c
