.TH "EcatDataSocket.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatDataSocket.h
.SH SYNOPSIS
.br
.PP
\fC#include 'NRMKDataSocket\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEcatDataSocket\fP"
.br
.RI "TCP/IP data socket for NRMK data scope\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint64_t \fBUINT64\fP"
.br
.ti -1c
.RI "typedef int64_t \fBINT64\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUINT32\fP"
.br
.ti -1c
.RI "typedef int32_t \fBINT32\fP"
.br
.ti -1c
.RI "typedef int16_t \fBINT16\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBUINT16\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBUINT8\fP"
.br
.ti -1c
.RI "typedef int8_t \fBINT8\fP"
.br
.ti -1c
.RI "typedef NRMKHelper::NRMKDataSocket< NUM_DATASCOPE_SIGNALS > \fB_ECAT_DATA_SOCKET\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNUM_JOINT\fP = 14, \fBNUM_WAIST\fP = 2, \fBNUM_LEFTARM\fP = 6, \fBNUM_RIGHTARM\fP = 6, \fBNUM_DATASCOPE_SIGNALS\fP = 6 * NUM_JOINT }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
2015-03-03 
.RE
.PP
\fBAuthor\fP
.RS 4
Thach Do 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
