.TH "EcatSystem/Ecat_Maxon.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatSystem/Ecat_Maxon.h \- Modified version of SimpleCAT\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Ecat_Slave\&.h'\fP
.br
\fC#include 'PDOConfig\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhyuEcat::EcatMaxon\fP"
.br
.RI "EtherCAT API for Maxon Epos4-EtherCAT 50/15\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhyuEcat\fP"
.br
.RI "EherCAT namespace for EtherLAB API\&. "
.in -1c
.SH "Detailed Description"
.PP 
Modified version of SimpleCAT\&. 


.PP
\fBDate\fP
.RS 4
2018-11-15 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
