.TH "EcatControlSocket.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatControlSocket.h \- TCP/IP data socket\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Poco/Event\&.h'\fP
.br
\fC#include 'NRMKSocketBase\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNRMKHelper::EcatControlSocket< _NUM_JOINTS >\fP"
.br
.RI "Ethernet control Socket\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBNRMKHelper\fP"
.br
.RI "NRMK TCP/IP namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
TCP/IP data socket\&. 


.PP
\fBDate\fP
.RS 4
2015-03-13 
.RE
.PP
\fBAuthor\fP
.RS 4
Thach Do 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
