.TH "EcatSystem/Ecat_Slave.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatSystem/Ecat_Slave.h \- EtherCAT slave base class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ecrt\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhyuEcat::Slave\fP"
.br
.RI "EtherCAT base class for each specific client i\&.e\&., ELMO, MAXON\&.\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBhyuEcat\fP"
.br
.RI "EherCAT namespace for EtherLAB API\&. "
.in -1c
.SH "Detailed Description"
.PP 
EtherCAT slave base class\&. 


.PP
\fBDate\fP
.RS 4
2018-11-11 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
