.TH "fb_t" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fb_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "unsigned char * \fBfp\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "long \fBscreen_size\fP"
.br
.ti -1c
.RI "int \fBline_length\fP"
.br
.ti -1c
.RI "int \fBbytes_per_pixel\fP"
.br
.ti -1c
.RI "int \fBbits_per_pixel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
