.TH "homing_info" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
homing_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBHomingOffset\fP"
.br
.ti -1c
.RI "int8_t \fBHomingMethod\fP"
.br
.ti -1c
.RI "uint32_t \fBHomingSpeed\fP"
.br
.ti -1c
.RI "uint16_t \fBHomingCurrentLimit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
