.TH "hyuCtrl" 3 "Wed Sep 25 2019" "Version 1.0.0" "Dual Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hyuCtrl \- control and trajecotry namespace for manipulator  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBController\fP"
.br
.RI "control algorithm for manipulator "
.ti -1c
.RI "class \fBMotion\fP"
.br
.ti -1c
.RI "class \fBTrajectory\fP"
.br
.RI "\fBTrajectory\fP Class is 5th order polynomial trajectory generator interface\&. "
.in -1c
.SH "Detailed Description"
.PP 
control and trajecotry namespace for manipulator 


.PP
\fBVersion:\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Arm Ver\&.1 from the source code\&.
