.TH "hyuCtrl::Motion" 3 "Wed Sep 25 2019" "Version 1.0.0" "Dual Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hyuCtrl::Motion
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhyuCtrl::Trajectory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAging\fP (float *_desired_pos)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Arm Ver\&.1 from the source code\&.
