.TH "HYUControl" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HYUControl \- control and trajecotry namespace for manipulator  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBController\fP"
.br
.RI "control algorithm for manipulator "
.ti -1c
.RI "class \fBKistHand\fP"
.br
.ti -1c
.RI "class \fBMotion\fP"
.br
.ti -1c
.RI "class \fBTrajectory\fP"
.br
.RI "\fBTrajectory\fP Class is 5th order polynomial trajectory generator interface\&. "
.in -1c
.SH "Detailed Description"
.PP 
control and trajecotry namespace for manipulator 


.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
