.TH "hyuEcat::Master::DomainInfo::Entry" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hyuEcat::Master::DomainInfo::Entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSlave\fP * \fBslave\fP = NULL"
.br
.ti -1c
.RI "int \fBnum_pdos\fP = 0"
.br
.ti -1c
.RI "unsigned int * \fBoffset\fP = NULL"
.br
.ti -1c
.RI "unsigned int * \fBbit_position\fP = NULL"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int* hyuEcat::Master::DomainInfo::Entry::bit_position = NULL"
position of slave 
.SS "int hyuEcat::Master::DomainInfo::Entry::num_pdos = 0"
number of pdo entries 
.SS "unsigned int* hyuEcat::Master::DomainInfo::Entry::offset = NULL"
alias of slave 
.SS "\fBSlave\fP* hyuEcat::Master::DomainInfo::Entry::slave = NULL"
slave pointer 

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
