.TH "HYUMotionBase" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HYUMotionBase \- Biorobotics Lab Lie-Group Operator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLieOperator\fP"
.br
.RI "Lie-algebra operator collection\&. "
.in -1c
.SH "Detailed Description"
.PP 
Biorobotics Lab Lie-Group Operator\&. 


.PP
\fBDate\fP
.RS 4
2018-08-13 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
