.TH "HYUMotionKinematics" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HYUMotionKinematics \- [Biorobotics Lab] Kinematics Solver using Lie-Group(Differential Kinematics)  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoEKinematics\fP"
.br
.RI "\fBPoEKinematics\fP Class for Tree-type Manipulator\&. "
.in -1c
.SH "Detailed Description"
.PP 
[Biorobotics Lab] Kinematics Solver using Lie-Group(Differential Kinematics) 


.PP
\fBVersion\fP
.RS 4
1\&.2\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
