.TH "HYUMotionDynamics" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HYUMotionDynamics \- Newton-Euler Dynamics expressed in Lie Group\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLiedynamics\fP"
.br
.RI "[Biorobotics Lab] Dynamics Solver using Lie-Group for Tree-type Manipulator "
.in -1c
.SH "Detailed Description"
.PP 
Newton-Euler Dynamics expressed in Lie Group\&. 


.PP
\fBVersion\fP
.RS 4
1\&.1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
