.TH "KDL/LieDynamics.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KDL/LieDynamics.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <Eigen/Dense>\fP
.br
\fC#include <Eigen/SVD>\fP
.br
\fC#include 'PropertyDefinition\&.h'\fP
.br
\fC#include 'PoEKinematics\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHYUMotionDynamics::Liedynamics\fP"
.br
.RI "[Biorobotics Lab] Dynamics Solver using Lie-Group for Tree-type Manipulator "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHYUMotionDynamics\fP"
.br
.RI "Newton-Euler Dynamics expressed in Lie Group\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Matrix< double, 6, 6 > \fBMatrix6d\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
2019-09-17 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
