.TH "LOGGING_PACK" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LOGGING_PACK
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBTime\fP"
.br
.ti -1c
.RI "double \fBActualPos\fP [BIONIC_ARM_DOF]"
.br
.ti -1c
.RI "double \fBActualVel\fP [BIONIC_ARM_DOF]"
.br
.ti -1c
.RI "short \fBActualToq\fP [BIONIC_ARM_DOF]"
.br
.ti -1c
.RI "double \fBDesiredPos\fP [BIONIC_ARM_DOF]"
.br
.ti -1c
.RI "double \fBDesiredVel\fP [BIONIC_ARM_DOF]"
.br
.ti -1c
.RI "short \fBDesiredToq\fP [BIONIC_ARM_DOF]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double LOGGING_PACK::ActualPos[BIONIC_ARM_DOF]"
Actual Position in Radian 
.br
 
.SS "double LOGGING_PACK::ActualVel[BIONIC_ARM_DOF]"
Actual Velocity in Radian/second 
.br
 
.SS "double LOGGING_PACK::Time"
Global Time 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
