.TH "EcatSystem/PDOConfig.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcatSystem/PDOConfig.h \- PDO configuration\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ecrt\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBElmo_VendorID\fP   0x0000009a"
.br
.ti -1c
.RI "#define \fBElmo_ProductCode\fP   0x00030924"
.br
.ti -1c
.RI "#define \fBKistHand_VendorID\fP   0x00000590"
.br
.ti -1c
.RI "#define \fBKistHand_ProductCode\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBKistSensor_VendorID\fP   0x00000581"
.br
.ti -1c
.RI "#define \fBKistSensor_ProductCode\fP   0x00000001"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ec_pdo_entry_info_t \fBElmo_pdo_entries\fP []"
.br
.ti -1c
.RI "ec_pdo_info_t \fBElmo_pdos\fP []"
.br
.ti -1c
.RI "ec_sync_info_t \fBElmo_syncs\fP [5]"
.br
.ti -1c
.RI "ec_pdo_entry_info_t \fBKistHand_pdo_entries\fP []"
.br
.ti -1c
.RI "ec_pdo_info_t \fBKistHand_pdos\fP []"
.br
.ti -1c
.RI "ec_sync_info_t \fBKistHand_syncs\fP [5]"
.br
.ti -1c
.RI "ec_pdo_entry_info_t \fBKistSensor_pdo_entries\fP []"
.br
.ti -1c
.RI "ec_pdo_info_t \fBKistSensor_pdos\fP []"
.br
.ti -1c
.RI "ec_sync_info_t \fBKistSensor_syncs\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
PDO configuration\&. 


.PP
\fBDate\fP
.RS 4
2019-05-30 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
