.TH "KDL/PoEKinematics.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KDL/PoEKinematics.h \- Product of Exponential formulation for Kinematics\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <Eigen/Dense>\fP
.br
\fC#include 'LieOperator\&.h'\fP
.br
\fC#include 'PropertyDefinition\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHYUMotionKinematics::PoEKinematics\fP"
.br
.RI "\fBPoEKinematics\fP Class for Tree-type Manipulator\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBHYUMotionKinematics\fP"
.br
.RI "[Biorobotics Lab] Kinematics Solver using Lie-Group(Differential Kinematics) "
.in -1c
.SH "Detailed Description"
.PP 
Product of Exponential formulation for Kinematics\&. 


.PP
\fBDate\fP
.RS 4
2019-09-17 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
