.TH "KDL/PropertyDefinition.h" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KDL/PropertyDefinition.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrobot_kinematic_info\fP"
.br
.RI "Kinematics Infomation\&. "
.ti -1c
.RI "struct \fBrobot_dynamic_info\fP"
.br
.RI "Dynamic Information\&. "
.ti -1c
.RI "struct \fBrobot_motor_info\fP"
.br
.RI "motor information "
.ti -1c
.RI "struct \fBFrictionMap\fP"
.br
.ti -1c
.RI "struct \fBFrictionTanh\fP"
.br
.ti -1c
.RI "struct \fBhoming_info\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBrobot_kinematic_info\fP \fBserial_Kinematic_info\fP []"
.br
.RI "Predefined kinematic object\&. "
.ti -1c
.RI "\fBrobot_dynamic_info\fP \fBserial_Dynamic_info\fP []"
.br
.RI "Predefined dynamic object\&. "
.ti -1c
.RI "\fBrobot_motor_info\fP \fBserial_Motor_info\fP []"
.br
.RI "Predefined system object\&. "
.ti -1c
.RI "\fBFrictionMap\fP \fBfrictionmap\fP []"
.br
.ti -1c
.RI "\fBFrictionTanh\fP \fBfrictiontanh\fP []"
.br
.ti -1c
.RI "\fBhoming_info\fP \fBhominginfo\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBDate\fP
.RS 4
2019-06-10 
.RE
.PP
\fBAuthor\fP
.RS 4
Junho Park 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
