.TH "robot_kinematic_info" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot_kinematic_info \- Kinematics Infomation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PropertyDefinition\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBw_x\fP"
.br
.ti -1c
.RI "double \fBw_y\fP"
.br
.ti -1c
.RI "double \fBw_z\fP"
.br
.ti -1c
.RI "double \fBq_x\fP"
.br
.ti -1c
.RI "double \fBq_y\fP"
.br
.ti -1c
.RI "double \fBq_z\fP"
.br
.ti -1c
.RI "double \fBl_x\fP"
.br
.ti -1c
.RI "double \fBl_y\fP"
.br
.ti -1c
.RI "double \fBl_z\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Kinematics Infomation\&. 
.SH "Member Data Documentation"
.PP 
.SS "double robot_kinematic_info::l_x"
Initial Configuration x-axis 
.SS "double robot_kinematic_info::l_y"
Initial Configuration y-axis 
.SS "double robot_kinematic_info::l_z"
Initial Configuration z-axis 
.SS "double robot_kinematic_info::q_x"
Twist x-axis 
.SS "double robot_kinematic_info::q_y"
Twist y-axis 
.SS "double robot_kinematic_info::q_z"
Twist z-axis 
.SS "double robot_kinematic_info::w_x"
Twist x-axis 
.SS "double robot_kinematic_info::w_y"
Twist y-axis 
.SS "double robot_kinematic_info::w_z"
Twist z-axis 

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
