.TH "Session::Data" 3 "Tue May 12 2020" "Version 1.0.0" "Bionic Arm Ver.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Session::Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbyte\fP [SIZE_DATA_MAX]"
.br
.ti -1c
.RI "double \fBdouble6dArr\fP [6]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Bionic Arm Ver\&.1 from the source code\&.
